const tableName = "tasks";

const seed = async function (knex) {
  await knex(tableName).truncate();
  await knex(tableName).insert([
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 1,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 2,
      completed: true,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 3,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 4,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 5,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 6,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 7,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 8,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 9,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 10,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 11,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 12,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 13,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 14,
      completed: false,
    },
    {
      title: "Check pre-filters pumps",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 15,
      completed: false,
    },

    {
      title: "Refill chlorine day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Refill chlorine day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Refill chlorine day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Refill chlorine day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Refill chlorine day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Refill chlorine day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },

    {
      title: "Refill chlorine day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Refill chlorine day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Refill sulfuric acid day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Refill sulfuric acid day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Refill sulfuric acid day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Refill sulfuric acid day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Refill sulfuric acid day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Refill sulfuric acid day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Refill sulfuric acid day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Refill sulfuric acid day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Refill locron day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Refill locron day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Refill locron day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Refill locron day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Refill locron day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Refill locron day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Refill locron day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Refill locron day tank",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Vacuuming",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Vacuuming",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Vacuuming",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Vacuuming",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Vacuuming",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Vacuuming",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Vacuuming",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Vacuuming",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Diving",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Diving",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Diving",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Diving",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Diving",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Diving",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Diving",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Diving",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Clean depolox pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Clean depolox pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Clean depolox pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Clean depolox pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Clean depolox pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Clean depolox pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Clean depolox pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Clean depolox pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 1,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 2,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 3,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 4,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 5,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 6,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 7,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 8,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 9,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 10,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 11,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 12,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 13,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 14,
      completed: false,
    },
    {
      title: "Clean sight glass pre-filter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 15,
      completed: false,
    },

    {
      title: "Check stock tank level",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Check stock tank level",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Check stock tank level",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Check stock tank level",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 4,
      completed: false,
    },

    {
      title: "Refill barrels",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Refill barrels",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 4,
      completed: false,
    },

    {
      title: "Empty quarantine",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },

    {
      title: "Remove salt deposits",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Remove salt deposits",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Remove salt deposits",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Remove salt deposits",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Remove salt deposits",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Remove salt deposits",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Remove salt deposits",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Remove salt deposits",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 1,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 2,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 3,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 4,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 5,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 6,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 7,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 8,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 9,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 10,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 11,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 12,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 13,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 14,
      completed: false,
    },
    {
      title: "Clean air vents",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 15,
      completed: false,
    },

    {
      title: "Drain pit submersible pump",
      visible: true,
      interval: "monthly",
      object_type: "department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Drain pit submersible pump",
      visible: true,
      interval: "monthly",
      object_type: "department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Drain pit submersible pump",
      visible: true,
      interval: "monthly",
      object_type: "department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Drain pit submersible pump",
      visible: true,
      interval: "monthly",
      object_type: "department",
      object_id: 4,
      completed: false,
    },

    {
      title: "Clean Depolox display",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Clean Depolox display",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Clean Depolox display",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Clean Depolox display",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 1,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 2,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 3,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 4,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 5,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 6,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 7,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 8,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 9,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 10,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 11,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 12,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 13,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 14,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 15,
      completed: false,
    },
    {
      title: "Calibration Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Calibration Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Calibration Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Calibration Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Calibration Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Calibration Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Calibration Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Calibration Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },
  ]);
};

export { seed };