const tableName = "measurement_logs";

const seed = async function (knex) {
  await knex(tableName).truncate();
  await knex(tableName).insert([
    {
      user_id: 2,
      sub_department_id: 1,
      measured_date: new Date("2025-06-08T03:24:00"),
      time: 1,
      comment: "Routine check, all good.",
      measurements: JSON.stringify({
        temp: 18.6,
        d_f_cl: 0.34,
        d_ph: 7.58,
        f_cl: 0.66,
        tot_cl: 0.93,
        comb_cl: 0.27,
        ph: 7.64,
        salt: 29,
        tot_col: 200,
        e_coli: 10,
      }),
    },
    {
      user_id: 1,
      sub_department_id: 1,
      measured_date: new Date("2025-06-08T04:15:00"),
      time: 2,
      comment: "Follow-up measurement, stable.",
      measurements: JSON.stringify({
        temp: null,
        d_f_cl: 0.32,
        d_ph: null,
        f_cl: 0.68,
        tot_cl: 0.95,
        comb_cl: 0.27,
        ph: null,
        salt: null,
        tot_col: null,
        e_coli: null,
      }),
    },
    {
      user_id: 0,
      sub_department_id: 3,
      measured_date: new Date("2025-06-08T05:00:00"),
      time: 1,
      comment: "New installation readings.",
      measurements: JSON.stringify({
        temp: 20.0,
        d_f_cl: 0.30,
        d_ph: 7.55,
        f_cl: 0.70,
        tot_cl: 1.00,
        comb_cl: 0.30,
        ph: 7.55,
        salt: 32,
        tot_col: 220,
        e_coli: 12,
      }),
    },
    {
      user_id: 2,
      sub_department_id: 8,
      measured_date: new Date("2025-06-08T06:30:00"),
      time: 2,
      comment: "Daily morning check.",
      measurements: JSON.stringify({
        temp: null,
        d_f_cl: 0.35,
        d_ph: null,
        f_cl: 0.65,
        tot_cl: 0.92,
        comb_cl: 0.27,
        ph: null,
        salt: null,
        tot_col: null,
        e_coli: null,
      }),
    },
    {
      user_id: 1,
      sub_department_id: 6,
      measured_date: new Date("2025-06-08T07:45:00"),
      time: 2,
      comment: "Afternoon data collection.",
      measurements: JSON.stringify({
        temp: null,
        d_f_cl: 0.33,
        d_ph: null,
        f_cl: 0.67,
        tot_cl: 0.94,
        comb_cl: 0.27,
        ph: null,
        salt: null,
        tot_col: null,
        e_coli: null,
      }),
    },
    {
      user_id: 0,
      sub_department_id: 6,
      measured_date: new Date("2025-06-08T08:50:00"),
      time: 1,
      comment: "End of day readings.",
      measurements: JSON.stringify({
        temp: 19.5,
        d_f_cl: 0.31,
        d_ph: 7.57,
        f_cl: 0.69,
        tot_cl: 0.98,
        comb_cl: 0.29,
        ph: 7.60,
        salt: 30,
        tot_col: 170,
        e_coli: 7,
      }),
    },
  ]);
};

export { seed };