const tableName = "tasks";

const seed = async function (knex) {
  await knex(tableName).truncate();
  await knex(tableName).insert([
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 1,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 2,
      completed: true,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 3,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 4,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 5,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 6,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 7,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 8,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 9,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 10,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 11,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 12,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 13,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 14,
      completed: false,
    },
    {
      title: "check voorfilters pompen",
      visible: true,
      interval: "daily",
      object_type: "pump",
      object_id: 15,
      completed: false,
    },

    {
      title: "opvullen dagtank chloor",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "opvullen dagtank chloor",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "opvullen dagtank chloor",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "opvullen dagtank chloor",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "opvullen dagtank chloor",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "opvullen dagtank chloor",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },

    {
      title: "opvullen dagtank chloor",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "opvullen dagtank chloor",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "opvullen dagtank zwavelzuur",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "opvullen dagtank zwavelzuur",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "opvullen dagtank zwavelzuur",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "opvullen dagtank zwavelzuur",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "opvullen dagtank zwavelzuur",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "opvullen dagtank zwavelzuur",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "opvullen dagtank zwavelzuur",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "opvullen dagtank zwavelzuur",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "opvullen dagtank locron",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "opvullen dagtank locron",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "opvullen dagtank locron",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "opvullen dagtank locron",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "opvullen dagtank locron",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "opvullen dagtank locron",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "opvullen dagtank locron",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "opvullen dagtank locron",
      visible: true,
      interval: "daily",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Stofzuigen",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Stofzuigen",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Stofzuigen",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Stofzuigen",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Stofzuigen",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Stofzuigen",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Stofzuigen",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Stofzuigen",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Duiken",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Duiken",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Duiken",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Duiken",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Duiken",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Duiken",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Duiken",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Duiken",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Schoonmaak voorfilter depolox",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Schoonmaak voorfilter depolox",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Schoonmaak voorfilter depolox",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Schoonmaak voorfilter depolox",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Schoonmaak voorfilter depolox",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Schoonmaak voorfilter depolox",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Schoonmaak voorfilter depolox",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Schoonmaak voorfilter depolox",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 1,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 2,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 3,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 4,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 5,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 6,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 7,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 8,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 9,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 10,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 11,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 12,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 13,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 14,
      completed: false,
    },
    {
      title: "Schoonmaak kijkglas voorfilter",
      visible: true,
      interval: "weekly",
      object_type: "pump",
      object_id: 15,
      completed: false,
    },

    {
      title: "Niveau voorraadvat checken",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Niveau voorraadvat checken",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Niveau voorraadvat checken",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Niveau voorraadvat checken",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 4,
      completed: false,
    },

    {
      title: "Aanvullen vaten",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Aanvullen vaten",
      visible: true,
      interval: "weekly",
      object_type: "department",
      object_id: 4,
      completed: false,
    },

    {
      title: "Quarantaine legen",
      visible: true,
      interval: "weekly",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },

    {
      title: "Verwijderen zout aanslag",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Verwijderen zout aanslag",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Verwijderen zout aanslag",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Verwijderen zout aanslag",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Verwijderen zout aanslag",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Verwijderen zout aanslag",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Verwijderen zout aanslag",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Verwijderen zout aanslag",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },

    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 1,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 2,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 3,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 4,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 5,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 6,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 7,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 8,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 9,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 10,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 11,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 12,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 13,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 14,
      completed: false,
    },
    {
      title: "Schoonmaken ontluchters",
      visible: true,
      interval: "monthly",
      object_type: "filter",
      object_id: 15,
      completed: false,
    },

    {
      title: "Afvoerput dompelpomp",
      visible: true,
      interval: "monthly",
      object_type: "department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Afvoerput dompelpomp",
      visible: true,
      interval: "monthly",
      object_type: "department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Afvoerput dompelpomp",
      visible: true,
      interval: "monthly",
      object_type: "department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Afvoerput dompelpomp",
      visible: true,
      interval: "monthly",
      object_type: "department",
      object_id: 4,
      completed: false,
    },

    {
      title: "Schoonmaken display Depolox",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Schoonmaken display Depolox",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Schoonmaken display Depolox",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Schoonmaken display Depolox",
      visible: true,
      interval: "monthly",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 1,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 2,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 3,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 4,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 5,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 6,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 7,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 8,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 9,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 10,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 11,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 12,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 13,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 14,
      completed: false,
    },
    {
      title: "Backwash",
      visible: true,
      interval: "none",
      object_type: "filter",
      object_id: 15,
      completed: false,
    },
    {
      title: "Calibratie Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 1,
      completed: false,
    },
    {
      title: "Calibratie Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 2,
      completed: false,
    },
    {
      title: "Calibratie Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 3,
      completed: false,
    },
    {
      title: "Calibratie Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 4,
      completed: false,
    },
    {
      title: "Calibratie Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 5,
      completed: false,
    },
    {
      title: "Calibratie Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 6,
      completed: false,
    },
    {
      title: "Calibratie Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 7,
      completed: false,
    },
    {
      title: "Calibratie Depolox",
      visible: true,
      interval: "none",
      object_type: "sub_department",
      object_id: 8,
      completed: false,
    },
  ]);
};

export { seed };